### ISSUE TITLE
Possible performance problem?

### ISSUE THREAD

**Issue by davagin** [p12tic/libsimdpp#41] opened 2016-05-27 17:16 UTC
I am trying to multiply two float32<8> numbers with SIMDPP_ARCH_X86_AVX setting.

The code something like:
float32<N> bigi = load(i);
float32<N> bigm = load(modifiers);
bigi = mul(bigi, bigm);

It works ok, but when I try to trace the code step-by-step I see that after multiplication the code goes to following piece of code:
template<class R, class T> SIMDPP_INL
R cast_memcpy(const T& t)
{
    static_assert(sizeof(R) == sizeof(T), "Size mismatch");
    R r;
    ::memcpy(&r, &t, sizeof(R));
    return r;
}

I don't understand why we need to do memcpy after each operation. It's a big performance gap.

**Comment by p12tic** [comment] 2016-05-27 19:52
Could it be that you are compiling without optimizations? In all supported compilers that memcpy is optimized out in the lowest optimization levels already.

**Comment by davagin** [comment] 2016-05-27 20:14
MSVS 2015. Maximum Speed (/O2)

**Comment by p12tic** [comment] 2016-05-27 21:36
Can't reproduce on MSVS 2013 on either of (none), /O1 and /O2 optimization levels. Could you please generate an assembly file (/c and /FA options) and attach it here?

**Comment by p12tic** [comment] 2016-05-27 21:49
We don't, however, use __forceinline for small functions, which led to MSVS 2013 not inlining them properly at /O1, which is not optimal. I've fixed this in 6d72631e8d58298b51.

**Comment by p12tic** [comment] 2016-06-02 09:52
I'm closing this issue for now. If you think I'm wrong and you have more information, please commend and reopen.

**Closed by p12tic** 2016-06-02 09:52 UTC
