### ISSUE TITLE
math ops fail to do int/float conversion or generate an error on SSE2

### ISSUE THREAD

**Issue by peabody-korg** [p12tic/libsimdpp#66] opened 2017-09-07 02:55 UTC
```
float32x4 foo(float32x4 a, int32x4 b)
{
    return a+b;
}
```
results in a single addps instruction for SSE2, as if b were a float32.

```
float32x4 foo(float32x4 a, int32x4 b)
{
    return add(a,b);
}
```
results in a compilation error, which is resolved by explicitly converting b with to_float32(). Presumably use of + should fail in the same was as use of add() (or even better would be to automatically convert between float/int just scalar operations would)

**Comment by p12tic** [comment] 2017-09-12 00:56
Thanks for the bug report. Unfortunately I can't reproduce the issue on neither the master branch nor C++11 or C++98 versions of the 2.0 release. Which version of libsimdpp are you using?

**Comment by peabody-korg** [comment] 2017-09-12 16:57
I'm at https://github.com/p12tic/libsimdpp/commit/2545b97da1d3fb7d5fd250741c4a4474d0005fc1 (libsimdpp-2.x branch, v2.0 tag). the problem appears to be isolated to xcode 8.3.3 and associated clang. In case it matters, I'm using SIMDPP_ARCH_X86_SSSE3, and using xcode's platform default vector set (which appears to be SSE 4.2).

**Comment by p12tic** [comment] 2017-10-06 17:49
Turns out this is caused by the [clang vector extension](https://clang.llvm.org/docs/LanguageExtensions.html#vectors-and-extended-vectors) ([corresponding GCC docs](https://gcc.gnu.org/onlinedocs/gcc/Vector-Extensions.html)). The extension defines various operators for the native SIMD types such as `__m128` and `__m128i`. With default options, one can write this code:
```
__m128i a;
__m128 b;

b = b + a; (results in addps)
```

This API was probably supposed to be used with the native clang vector types that expose more information about the type of data within them. Extending this API to types such as `__m128i` seems to be poor design choice, as they correspond to several different data layouts. For example, addition of two `__m128i` quantities always results in `paddq` instruction.

With regards to libsimdpp, this revelation is unfortunate, because code like this will result in wrong behavior instead of failing to compile:

```
int8<16> foo (int8<16> a, int16<8> b)
{
    // the following invokes int8<16>::native_type() and int16<8>::native_type() conversion
    // operators, retrieves two __m128i quantities and adds them via paddq instruction
    return a + b; 
}
```

Unfortunately there seems no way to disable the operators provided by the vector extension. There is `-fno-lax-vector-conversions` option, but it still allows adding two `__m128i` variables, so it's not a solution. If this information is correct, then the native_type() operators will need to be removed eventually, which means that it no longer will be possible to write code like this:
```
int8<16> a, b;
a = _mm_add_epi8(a, b);
```
As a replacement, a member function will be added which will enable the code to be rewritten like this:
```
int8<16> a, b;
a = _mm_add_epi8(a.native(), b.native());
```

**Comment by p12tic** [comment] 2017-10-08 19:32
Member function to retrieve native vector value to all vector types have been added in 40ba6dd02662ab4aca636b0a2ae33ed03f7a8617.

The usage of the old conversion operator throughout the library have been removed in ba136bf48235056c5ff45a191184d903ff7f55f8.

Tests to verify that wrong conversions are no longer accepted have been added in in afd87085eaf9bca269986c31f894d5027acba671.

The old conversion operators have been marked as deprecated in cac38571803f5016001bcc35c8cd734ca3229564. The API will be removed some time in the future.

If one wants to disable the old operators to avoid this bug, `SIMDPP_DEFINE_IMPLICIT_CONVERSION_OPERATOR_TO_NATIVE_TYPES` can be defined to 0.

**Closed by p12tic** 2017-10-08 19:32 UTC
